[dev] update s3 flow to add bucket ownership control
Securezapp/cartography pull request #29
Opened 2023-05-11 11:24 UTC by ashwin-borneo

Use get_bucket_ownership_control to fetch and update ownership control information per bucket. Defaults to 'ObjectWriter' if ObjectOwnershipNotFoundError occurs

2023-05-11 17:19 UTC, jhecking requested changes
I think changing the name from "bucket ownership controls" to "object ownership" just makes this more confusing. I agree that "object ownership" in a way is a better name for this concept than "bucket ownership" but still think it's overall better to stay consistent with AWS naming. Can you please apply `s/object_ownership/bucket_ownership_controls/g` once over this entire code?

2023-05-12 01:51 UTC, ashwin-borneo commented
> object_ownership

Done.

2023-05-12 09:36 UTC, jhecking commented
> > object_ownership
> 
> Done.

I only just saw that AWS themself use the term "object ownership" in the actual API response! 🤦 

```
    # 'OwnershipControls': {
     #    'Rules': [
     #        {
     #            'ObjectOwnership': 'BucketOwnerPreferred'|'ObjectWriter'|'BucketOwnerEnforced'
     #        },
     #    ]
     #  }
```

Had I noticed this earlier, I would not have asked you to change your naming. So sorry! 🙇

2023-05-12 09:36 UTC, jhecking approved these changes

2023-05-12 09:39 UTC, merged