BOR-2927: adds setting borneo_id on create
Securezapp/cartography pull request #3
Opened 2022-09-06 07:10 UTC by ongteckwu

2022-09-07 03:12 UTC, jhecking commented on cartography/intel/aws/apigateway.py
> +    rest_api.borneo_id = {rest_api_borneo_id}
Should `borneo_id` be set under the `ON CREATE SET` clause? Because we never want to update the ID if the node already exists.

But maybe my understanding of Cypher is wrong. I was going by this example here: https://neo4j.com/docs/cypher-manual/current/clauses/merge/#merge-merge-with-on-create-and-on-match. That example uses `MERGE` with both `ON CREATE SET` and `ON MATCH SET`, whereas this query uses `ON CREATE SET` with just `SET` – not sure if that makes any difference?

2022-09-07 03:59 UTC, ongteckwu commented on cartography/intel/aws/apigateway.py
> +    rest_api.borneo_id = {rest_api_borneo_id}
So `ON CREATE SET` is only done on create, and then there's `SET` which is done at every update or insert.

2022-09-07 04:00 UTC, jhecking commented on cartography/intel/aws/apigateway.py
> +    rest_api.borneo_id = {rest_api_borneo_id}
Yes, exactly! We don't want to set the `borneo_id` on every update, but just on create, right?

2022-09-07 04:02 UTC, jhecking commented on cartography/intel/aws/apigateway.py
> +    rest_api.borneo_id = {rest_api_borneo_id}
I.e. `borneo_id` should be handled like `rest_api.createddate`, not like `rest_api.lastupdated`.

2022-09-07 05:53 UTC, ongteckwu commented on cartography/intel/aws/apigateway.py
> +    rest_api.borneo_id = {rest_api_borneo_id}
oh yes. I wrote on the wrong line. Thanks.

2022-09-07 06:46 UTC, jhecking requested changes
Few borneo_ids still in the wrong part of the upsert statement. Also couple of typos – surprised Python doesn't catch those automatically?

2022-09-07 06:46 UTC, jhecking commented on cartography/intel/aws/apigateway.py
> +    rest_api.borneo_id = {rest_api_borneo_id}
Move to "ON CREATE SET" statement.

2022-09-07 06:46 UTC, jhecking commented on cartography/intel/aws/apigateway.py
> +    c.borneo_id = {cert_borneo_id}
Move to "ON CREATE SET" statement.

2022-09-07 06:46 UTC, jhecking commented on cartography/intel/aws/elasticache.py
> +            topic.borneo_id = {topic_borneo_id}
Interesting: Cartography doesn't supports SNS topics as separate resources, but only supports SNS topics that are used as notification targets for ElastiCache cluster!? Weird choice.

2022-09-07 06:46 UTC, jhecking commented on cartography/intel/aws/kms.py
> +    a.borneo_id = {alia_borneo_id}
```suggestion
    a.borneo_id = {alias_borneo_id}
```

2022-09-07 06:46 UTC, jhecking commented on cartography/intel/aws/kms.py
> +    kmskey.borneo_id = {kms_borneo_id}
Move to "ON CREATE SET" statement.

2022-09-13 03:12 UTC, jhecking approved these changes

2022-09-13 10:29 UTC, merged